name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - name: test
        run: ls -a
        
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@1.2.0
        with:
          working_directory: '/'
          root_file: 'main.tex'
 
    
