name: Latex
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile and Deploy LaTeX to PDF
      uses: xu-cheng/latex-action@1.2.0
      with:
          root_file: main.tex
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: ""
        GH_PAT: ${{ secrets.GH_PAGES_PAT }}
