name: Latex
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test
      run: ls -a;
          cd ..; ls -a;
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@1.2.0
      with:
          root_file: main.tex
    - name: test
      run: ls -a;
          cd ..; ls -a;
    - name: upload
      uses: actions/upload-artifact@master
      with:
        name: main.pdf
        path: ./
      env:
        CI: true
