name: Latex
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile LaTeX to PDF
      uses: dante-ev/latex-action@v0.2.0
      with:
        # The root LaTeX file to be compiled
        root_file: main.tex
        # LaTeX engine to be used
        compiler: pdflatex # optional, default is latexmk          
    - name: Move main.pdf
      run: mkdir build; mv main.pdf build/;
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: "build/"
        GH_PAT: ${{ secrets.GH_PAGES_PAT }}
