name: Latex
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@1.2.0
      with:
          root_file: main.tex
    - name: upload
      uses: skx/github-action-publish-binaries@master
      with:
        name: main.pdf
        path: ./main.pdf
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
